name: Jekyll build and publish to other repo
description: 'Builds & deploys Jekyll to another repos gh-pages'

DEST_REPO:
  description: 'Repository to push file to. Example: gh_user/repo_name'
  required: true

GH_TARGET_REPO_TOKEN:
  description: 'Github token for this action (create this in your settings)'
  required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding: 
  icon: 'shield'
  color: 'blue'

