name: Jekyll build and publish to other repo
description: 'Builds & deploys Jekyll to another repos gh-pages'

DEST_REPO:
  description: 'Repository to push file to. Example: gh_user/repo_name'
  required: true

DEST_REPO_DEPLOY_KEY:
  description: 'private ssh key for this action. public key goes in dest secret settings'
  required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding: 
  icon: 'shield'
  color: 'blue'

